### ISSUE TITLE
Forced image override on user profile update

### ISSUE THREAD

**Issue by matasarei** [MFreakNL/moodle-block_mfavatar#5]
Hello @luukverhoeven !

I found a nasty bug in your plugin, please checkout this screencast:
https://youtu.be/uKX71bE7jks

and suggested fix:
https://github.com/MFreakNL/moodle-block_mfavatar/pull/4/files

**Comment by luukverhoeven** [comment]
Hi @matasarei  

Thanks for finding this issue. I have merge your pull request! 
I will add your name in **Contributing** list.
